Tag the rocm-smi-lib git dir to get the correct so version
By default we will get librocm_smi64.so.1, which causes the
flash-attention build fail with:

ImportError: librocm_smi64.so.7: cannot open shared object file: No such file or directory